version: '3.8'

services:

  api:
    build:
      context: ./social_network/
      dockerfile: Dockerfile
    command: gunicorn social_network.wsgi:application --bind 0.0.0.0:8001 # for production
    # command: python manage.py runserver 0.0.0.0:8000 #for local

    ports:
      - "8001:8001"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"