name: Count Lines of Code in External Repo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  count_lines_of_code:
    runs-on: ubuntu-latest

    steps:
      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Clone external repository
        run: git clone https://github.com/lesanabbas/Connectify.git

      - name: Create social_network directory if it doesn't exist
        run: |
          mkdir -p ../social_network  # Creates the directory if it doesn't exist

      - name: Count lines of code in external repository and store output in social_network folder
        run: |
          cd Connectify
          cloc . --json > ../social_network/cloc_output.json  # Save output in social_network folder

      - name: List files to confirm output file is in social_network folder
        run: ls -la ../social_network  # This will list files in the social_network folder
