name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image with Docker Compose
      env:
        POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      run: |
        docker-compose up --build -d
        docker-compose down
        docker tag social-media ${{ secrets.DOCKER_USERNAME }}/social-media
        docker push ${{ secrets.DOCKER_USERNAME }}/social-media

    - name: Logout from Docker Hub
      run: docker logout
